# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ uploadOracleAngular ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build Backend and Deploy it
  buildAndDeployBackend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Assemble JAR'
        run: |
          mvn clean package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: SP-Backend.jar
          # A file, directory or wildcard pattern that describes what to upload
          path: Backend/target/*jar-with-dependencies.jar
      - name: kill Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ps -ef | grep 'SP-Backend' | grep -v grep | awk '{print $2}' | xargs -r kill -9
      - name: Publish to Oracle Cloud
        uses: nogsantos/scp-deploy@master
        with:
          src: Backend/target/*jar-with-dependencies.jar
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
      - name: Run Backend in Background
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: nohup java -jar SP-Backend/SP-Backend-1.0-SNAPSHOT-jar-with-dependencies.jar < /dev/null > /dev/null 2> /dev/null &


  buildAndDeployFrontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
        working-directory: Frontend/SPFrontend
      #- name: Test
      #  run: npm run --prefix Frontend/SPFrontend test
      - name: Build
        run: npm run --prefix Frontend/SPFrontend build
      - name: Clear directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo rm -r /var/www/html/*
      - name: Publish to Oracle Cloud
        uses: nogsantos/scp-deploy@master
        with:
          src: Frontend/SPFrontend/dist/SPFrontend
          host: ${{ secrets.SSH_HOST }}
          remote: /var/www/html
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
      - name: Restart HTTP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo httpd -k restart