# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ uploadOracle ]
  pull_request:
    branches: [ uploadOracle ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Assemble JAR'
        run: |
          mvn clean package
      - name: ls
        run: ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: SP-Backend.jar # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: Backend/target/*jar-with-dependencies.jar
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OC_HOST }}
          username: opc
          key: ${{ secrets.OC_PRIVATE_KEY }}
          port: 22
          script: scp Backend/target/SP-Backend-1.0-SNAPSHOT-jar-with-dependencies.jar ocp@${{ secrets.OC_HOST }}:/home/ocp/SP-Backend