name: 'Unit Tests'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ SP-80 ]
  pull_request:
    branches: [ SP-80 ]


jobs:
  # Build Backend and Deploy it
  MavenTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: 'mvn test'
        run: |
            mvn test

#  AngularTest:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#      - name: 'Setup Node.js'
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#      - name: 'npm-install'
#        run: npm install
#        working-directory: Frontend/SPFrontend
#
#      - name: 'install angular'
#        run: npm install -g @angular/cli
#        working-directory: Frontend/SPFrontend
#
#      - name: 'Install protractor'
#        run: npm install -g protractor
#        working-directory: Frontend/SPFrontend
#
#
#      - name: 'update protractor webdriver'
#        run: webdriver-manager update
#        working-directory: Frontend/SPFrontend
#
#      - name: 'Install firefox addon'
#        run: npm install protractor-firefox-support --save
#        working-directory: Frontend/SPFrontend
#
#      - name: 'run protractor'
#        run: protractor protractor.conf.js
#        working-directory: Frontend/SPFrontend/e2e/
